name: "Deploy documentation"

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy odoc to GitHub Pages
        uses: smorimoto/ocaml-actions/deploy-doc@master
